# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

require "faker"

user = User.create(name: "Addison Martin", email: Rails.application.credentials.default_user_email, password: Rails.application.credentials.default_user_password, password_confirmation: Rails.application.credentials.default_user_password, confirmed_at: DateTime.now)

Page.create(title: "Home", body: "<blockquote><strong><em>\"Life’s persistent and most urgent question is, 'What are you doing for others?'\"</em></strong><br><br><em>- Martin Luther King Jr.</em></blockquote><div><br></div><h1><strong>What We Do</strong></h1><div>Many of our neighbours are fleeing unimaginable violence. In the process, they've lost almost everything. The future seems bleak.</div><div><br></div><div>With your help, they can begin to pick up the pieces to start again. One important way is to help them furnish their new home.&nbsp;</div><div><br></div><div>Through this website, we connect generous donors with local charities to ensure gently-used household items can find a new home.</div><div><br><br></div><h1><strong>Do you want to donate something?</strong></h1><div>We hope to connect gently used household items with individuals and families that might need them.</div><div><br></div><div>We value dignity as well as generosity. Therefore, please don't offer dirty, broken, stained or torn items.&nbsp;</div><div><br><br></div><h1><strong>Does your charity need something?</strong></h1><div>As a registered charity, your work is the cornerstone of helping others.</div><div><br></div><div>Please tell us a little about the work you do. Be sure to include your Canadian Charity registration number and contact information.</div><div><br></div><div><br></div><h1><strong>Q&amp;A</strong></h1><div><em>Q. What about picking up and dropping off donations?</em></div><div>A. Once a connection is made, it will be up to the donor and the charity to arrange for transportation.</div><div><br></div><div><em>Q. What are examples of household items?</em></div><div>A. Household furniture! This includes working appliances. Pots, pans, plates, bowls, cutlery are always needed.&nbsp;</div><div><br></div><div>Pictures and other decorative items can make a house feel more like a home.</div><div><br></div><div>Small carpets!</div><div><br></div><div>Some electronics. Old TVs and VCRs should not be offered.</div><div><br></div><div><em>Q. What is gently used?</em></div><div>A. Gently-used' is tricky to define. Before donating something, perhaps ask yourself if someone in your family would accept the donation if they needed it. If the answer is yes, this website is for you!</div><div><br></div><div><em>Q. What about large, bulky items like china cabinets, office cabinets and sectional couches?</em></div><div>A. These are less popular as they can be difficult to move. And they can take up lots of space in smaller apartments.</div><div><br></div><div><em>Q. Once my donation is posted, does it stay up until a charity claims it?</em></div><div>A. Posts only stay up for 10 days.</div><div><br></div><div><em>Q. How do I claim a donation?</em></div><div>A. View the donation and select the claim button. You must be both signed in and belonging to a charity!</div>", user: user)
