name: Continuous Integration

on:
  [ pull_request, push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup test database
        run: bundle exec rails db:prepare

      - name: Setup test assets
        run: bundle exec rails assets:precompile
      
      - name: Lint code for consistent style
        run: bin/rubocop -f github
      
      - name: Lint .html.erb files for consistent style and safety
        run: bundle exec erb_lint --lint-all
      
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
      
      - name: Scan Ruby dependencies for out of date, insecure versions
        run: bundle exec bundle-audit check --update
      
      - name: Scan Javascript dependencies for out of date, insecure versions
        run: yarn audit
      
      - name: Run code and application tests
        run: bundle exec rspec

